-- 1. Cria a tabela de bilhetes com validação de unicidade
create table bilhetes (
  id bigint generated by default as identity primary key,
  numero integer not null unique, -- Garante que o número não se repete
  comprador text,                 -- Opcional: Nome do comprador
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Habilita o "Realtime" (Websockets) para esta tabela
-- Isso permite que o Frontend "escute" quando novos bilhetes são inseridos
alter publication supabase_realtime add table bilhetes;

-- 3. Tabela de Histórico de Vencedores (Dashboard)
CREATE TABLE IF NOT EXISTS public.historico_vencedores (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_sorteado integer NOT NULL,
    premio_valor numeric,
    data_sorteio timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Políticas de Segurança (Modo Público / Demo)
alter table bilhetes enable row level security;
alter table historico_vencedores enable row level security;

-- Políticas para Bilhetes
create policy "Permitir Insert Publico Bilhetes" on bilhetes for insert with check (true);
create policy "Permitir Leitura Publica Bilhetes" on bilhetes for select using (true);
create policy "Permitir Delete Publico Bilhetes" on bilhetes for delete using (true);

-- Políticas para Histórico
create policy "Leitura pública histórico" ON public.historico_vencedores FOR SELECT USING (true);
create policy "Inserção pública histórico" ON public.historico_vencedores FOR INSERT WITH CHECK (true);
