# Generated by Django 6.0.1 on 2026-01-07 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=50)),
                ('detalhes', models.TextField()),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Grande Sorteio', max_length=100)),
                ('valor_premio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_ganhadores', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada')], default='ABERTA', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bilhete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('comprador_nome', models.CharField(max_length=100)),
                ('comprado_em', models.DateTimeField(auto_now_add=True)),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilhetes', to='core_rifa.rifa')),
            ],
            options={
                'indexes': [models.Index(fields=['rifa', 'numero'], name='core_rifa_b_rifa_id_04f3eb_idx')],
                'unique_together': {('rifa', 'numero')},
            },
        ),
    ]
